name: ðŸ“ˆ Bump Version (mirror-web-server)

on:
  push:
    branches:
    - 'dev'
    paths:
    - mirror-web-server/**
    - .github/**

jobs:
  bump-version:
    name: 'Upgrade version'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'cat package.json'
        run: cat ./mirror-web-server/package.json

      - name: Automated Version Bump
        id: version_bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          major-wording: 'release-major'
          minor-wording: 'release-minor'
          #   # defaults to a patch bump.
          rc-wording: 'rc'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET_WRITE_TOKEN }}
          PACKAGEJSON_DIR: ./mirror-web-server

      - name: cat package.json
        run: cat ./mirror-web-server/package.json

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version_bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
